name: Github Actions Test

on:
  workflow_dispatch:
    inputs:
      input_boolen:
        type: boolean
        required: true
        description: Test Input
        default: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "echo env"
        run: |
          echo ${{github.event.inputs.input_boolen}}
      - name: "Test Step"
        if: ${{github.event.inputs.input_boolen == 'true'}}
        run: |
          echo "TEST OK"