name: Run Test

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        description: Twitcasting Video Url

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Docker Test
        run: |
          docker run -e TWITCASTING_URL=${{github.event.inputs.url}} -e ONEDRIVE_TOKEN_URL=${{ secrets.ONEDRIVE_TOKEN_URL }} -e ONEDRIVE_TOKEN_KEY=${{ secrets.ONEDRIVE_TOKEN_KEY }} ${{ secrets.DOCKER_HUB_USERNAME }}/twitcasting_dl:debug
